
name: Build and deploy ASP.Net Core app to Azure Web App - bydevopsdemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

#build the code, you done need action here. we have setup the dotnet in the above step so we can just use the run: command
      - name: Build the app with dotnet
        run: dotnet build --configuration Release


#run automated tests
     # - name: Run automated tests
     # - run: dotner test --configuration Release

      - name: publish app
        run: dotnet publish --configuration Release -o ./out


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testopsdev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4096909440B8472FBFBD0FE4E9AD692D }}
          package: ./out